name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: '0 0 1 1 *' # Run yearly
  workflow_dispatch:
    # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCYI5IR2pNZ8pJn9RuJiUjAQ